<?php
	
// REMOVE SIDE MENU ITEMS
function remove_jupiter_menu_items() {
	remove_menu_page( 'edit-comments.php' );
	remove_menu_page( 'wpforms-overview' );
	remove_menu_page( 'mojo-marketplace' );
	remove_menu_page( 'vc-general' );
	remove_menu_page( 'monsterinsights_settings' );
	remove_menu_page( 'optin-monster-api-settings' );
	remove_menu_page( 'jetpack' );
	remove_menu_page( 'admin.php?page=masterslider' );
	remove_menu_page( 'admin.php?page=masterslider' );
	remove_menu_page( 'admin.php?page=flow-flow' );
	remove_menu_page( 'admin.php?page=layerslider' );
	remove_menu_page( 'admin.php?page=wpseo_dashboard' );
	remove_menu_page( 'admin.php?page=vc-welcome' );

	//posts
 	//remove_menu_page( 'edit.php' );
	//pages
	//remove_menu_page( 'edit.php?post_type=page' );
   
}
add_action( 'admin_menu', 'remove_jupiter_menu_items',999 );

// REMOVE JUPITER POST TYPES
function delete_jupiter_post_types(){
    unregister_post_type( 'clients' );
    unregister_post_type( 'animated-columns' );
    unregister_post_type( 'edge' );
    unregister_post_type( 'employees' );
    unregister_post_type( 'faq' );
    unregister_post_type( 'news' );
    unregister_post_type( 'portfolio' );
    unregister_post_type( 'pricing' );
    unregister_post_type( 'tab_slider' );
    unregister_post_type( 'testimonial' );
    unregister_post_type( 'photo_album' );
}
add_action('init','delete_jupiter_post_types');

// REMOVE ITEMS FROM ADMIN BAR
function remove_admin_bar_items($wp_admin_bar) {
    /*
     * Placing items in here will only remove them from admin bar
     * when viewing the front end of the site
    */
    if ( ! is_admin() ) {
        // Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu
        $wp_admin_bar->remove_node('ubermenu');
        $wp_admin_bar->remove_node('wpseo-menu');
        $wp_admin_bar->remove_node('gform-forms');
        $wp_admin_bar->remove_node('comments');
        $wp_admin_bar->remove_node('updates');
        $wp_admin_bar->remove_node('search');
        $wp_admin_bar->remove_node('my-account');
        $wp_admin_bar->remove_node('wp-logo');
        $wp_admin_bar->remove_node('clean_dynamic_styles');
    }

    /*
     * Items placed outside the if statement will remove it from both the frontend
     * and backend of the site
    */
    $wp_admin_bar->remove_node('wp-logo');
}
add_action('admin_bar_menu', 'remove_admin_bar_items', 999);
